### ISSUE TITLE
help me!

### ISSUE THREAD

**Issue by tungtomvn** [drumnkyle/music-notation-kit#4]
Can you post example code? Please!

**Comment by drumnkyle** [comment]
This library is still under development and is not yet ready for use. If you are interested in helping contribute, let me know. Otherwise, the library will be marked as version 1.0 once it’s ready. To follow along the development, most of it is being done in music notation core right now. This library will have the final wrapper as well UI layer, but the UI layer hasn’t been started as there is still necessary work to be completed on the core.

**Comment by tungtomvn** [comment]
Thank you for your reply. But I don't know much about it, I'm doing an application for guitar and related to this part.
